### ISSUE TITLE
Dropbox-0.1 inform user on Slack incorrectly

### ISSUE THREAD

**Issue by DevonCurrent** [DevonCurrent/DropboxSearchTool#2]
When I try to send a message to the bot without any file name (just include -fn without anything after), I expect to see the bot tell me there was an error with the request. It send the error, but sends each letter separately of the sentence.

To recreate this error, type in "@capstonebot -fn" without quotes.

**Comment by rcahler** [comment]
Pushed fix, error string was not enclosed within brackets so was being passed as the wrong data type.
