### ISSUE TITLE
Dropbox-0.1 Slack bot returns all files on dropbox.

### ISSUE THREAD

**Issue by DevonCurrent** [DevonCurrent/DropboxSearchTool#3]
When I make a request to see a file through the Slack bot, I expect to get files related to the search. Instead, I receive files from everything on the Dropbox.

To recreate this, I typed in "@Capstone Bot -fn money" while set up to the testing slack and dropbox server.

**Comment by rcahler** [comment]
The relevant flag was not being set.

**Comment by rcahler** [comment]
In cases where neither a year or company was given, the program never checked whether or not a file was relevant to the search, instead returning the whole dropbox.
