### ISSUE TITLE
Dropbox-0.1 Dropbox does not search through by year(s)

### ISSUE THREAD

**Issue by DevonCurrent** [DevonCurrent/DropboxSearchTool#4]
When I try to search for files in a specific year(s), it should return files only related to those years. Instead it returned everything, and was not related to the year of the file(s).

I typed in "@Capstone Bot -fn leader -y 2014" while accessing the testing slack and dropbox server.

**Comment by rcahler** [comment]
The case where the year flag was set and the company flag was not was missing the check against the flag.
