### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by rcahler** [DevonCurrent/DropboxSearchTool#8]
4 tests in DropboxSearchToolTests are returning errors and not passing.

**Comment by rcahler** [comment]
All of the tests are failing

**Comment by DevonCurrent** [comment]
The TestDropboxSearchTools has been renamed to TestMessageParsing (as this was most of the former's functionality).  This tests that messages are parsed correctly into Search objects that can then be used to make searches on Dropbox.
